version: "2.1"
services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:9.0.1
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10